### ISSUE TITLE
Cannot build App

### ISSUE THREAD

**Issue by Bellusterra** [nextcloud/flow_notifications#6]
Hello, I'm not sure if I'm doing something wrong, but followed the instructions per the github page. Cloned into apps folder of Nexcloud changed directory to flow_notifications folder and ran command "npm ci && npm run dev"

- npm ci command gives me:

```
Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install,
    install-test, issues, it, la, link, list, ll, ln, login,
    logout, ls, outdated, owner, pack, ping, prefix, prune,
    publish, r, rb, rebuild, remove, repo, restart, rm, root,
    run-script, s, se, search, set, show, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unlink, unpublish, unstar, up, update, upgrade, v, verison,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /root/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config
```

- npm run dev command gives me:

 
```
> flow_notifications@1.0.0 dev /media/2TB-MIRROR/container-volumes/nextcloud/apps/flow_notifications
> NODE_ENV=development webpack --progress --config webpack.js

sh: 1: webpack: not found

npm ERR! Linux 5.4.0-42-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! flow_notifications@1.0.0 dev: `NODE_ENV=development webpack --progress --config webpack.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the flow_notifications@1.0.0 dev script 'NODE_ENV=development webpack --progress --config webpack.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flow_notifications package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development webpack --progress --config webpack.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flow_notifications
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flow_notifications
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/2TB-MIRROR/container-volumes/nextcloud/apps/flow_notifications/npm-debug.log
```

- The npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle flow_notifications@1.0.0~predev: flow_notifications@1.0.0
6 silly lifecycle flow_notifications@1.0.0~predev: no script for predev, continuing
7 info lifecycle flow_notifications@1.0.0~dev: flow_notifications@1.0.0
8 verbose lifecycle flow_notifications@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle flow_notifications@1.0.0~dev: PATH: /usr/share/npm/bin/node-gyp-bin:/media/2TB-MIRROR/container-volumes/nextcloud/apps/flow_notifications/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle flow_notifications@1.0.0~dev: CWD: /media/2TB-MIRROR/container-volumes/nextcloud/apps/flow_notifications
11 silly lifecycle flow_notifications@1.0.0~dev: Args: [ '-c',
11 silly lifecycle   'NODE_ENV=development webpack --progress --config webpack.js' ]
12 info lifecycle flow_notifications@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: flow_notifications@1.0.0 dev: `NODE_ENV=development webpack --progress --config webpack.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid flow_notifications@1.0.0
15 verbose cwd /media/2TB-MIRROR/container-volumes/nextcloud/apps/flow_notifications
16 error Linux 5.4.0-42-generic
17 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error flow_notifications@1.0.0 dev: `NODE_ENV=development webpack --progress --config webpack.js`
24 error spawn ENOENT
25 error Failed at the flow_notifications@1.0.0 dev script 'NODE_ENV=development webpack --progress --config webpack.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the flow_notifications package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     NODE_ENV=development webpack --progress --config webpack.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs flow_notifications
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls flow_notifications
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by rullzer** [comment]
Your node and npm version are very old. Please upgrade both to a more recent one and try again.

**Comment by Bellusterra** [comment]
@rullzer Thank you.
